version: "3"
services:
  myapp:
    image: phpmyadmin:latest
    ports:
    - target: 80
      published: __PORT__
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      - PMA_ABSOLUTE_URI=__DOMAIN____PATH__
      - PMA_HOST=host.docker.internal
      - PMA_PORT=3306
      - PMA_USER=__DB_USER__
      - PMA_PASSWORD=__DB_PWD__
      - HIDE_PHP_VERSION=true
